create table if not exists public.supervisors (
    id bigint generated by default as identity primary key,
    name text not null,
    pin text not null unique,
    created_at timestamptz not null default now()
);

alter table public.face_profiles
add column if not exists supervisor_id bigint references public.supervisors (id) on delete restrict;

create or replace function public.validate_supervisor_pin(pin_input text)
returns table (supervisor_id bigint, supervisor_name text)
language plpgsql
security definer
set search_path = public
as $$
begin
    return query
    select s.id, s.name
    from public.supervisors s
    where s.pin = trim(pin_input)
    limit 1;
end;
$$;

revoke all on function public.validate_supervisor_pin(text) from public;
grant execute on function public.validate_supervisor_pin(text) to anon, authenticated;

-- Exemplo de supervisores iniciais
-- insert into public.supervisors (name, pin) values
-- ('Supervisor A', '1234'),
-- ('Supervisor B', '5678');
