create table if not exists public.games_catalog (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    summary text,
    implementation_key text not null default 'future_game',
    status text not null default 'planned',
    active boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.player_game_assignments (
    id bigint generated by default as identity primary key,
    player_profile_id uuid not null references public.face_profiles (id) on delete cascade,
    game_code text not null,
    difficulty text not null default 'medium',
    enabled boolean not null default true,
    sort_order integer not null default 1,
    assigned_by_supervisor_id bigint references public.supervisors (id) on delete set null,
    created_at timestamptz not null default now()
);

create index if not exists idx_player_game_assignments_player
on public.player_game_assignments (player_profile_id, sort_order);

create unique index if not exists idx_player_game_assignments_unique_game
on public.player_game_assignments (player_profile_id, game_code);

alter table public.player_game_assignments
    drop constraint if exists player_game_assignments_difficulty_check;

alter table public.player_game_assignments
    add constraint player_game_assignments_difficulty_check
    check (difficulty in ('easy', 'medium', 'hard'));

-- Exemplos para quando os jogos estiverem prontos:
-- insert into public.games_catalog (code, name, summary, implementation_key, status, active) values
-- ('lower_right', 'Membros Inferiores - Direita', 'Exercicios de perna direita.', 'games2_lower_right', 'ready', true),
-- ('waist', 'Cintura', 'Inclinacao e rotacao do tronco.', 'games2_waist', 'ready', true);

-- insert into public.player_game_assignments (player_profile_id, game_code, difficulty, enabled, sort_order, assigned_by_supervisor_id) values
-- ('uuid-do-jogador', 'lower_right', 'medium', true, 1, 1);
